# name: Deploy to Github Pages

# on:
#   push:
#     branches:
#     - main
# permissions:
#   pages: write
#   id-token: write

# jobs:
#   deploy:
#     runs-on: ubuntu-latest


#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Upload to github pages
#         uses: actions/upload-pages-artifact@v3

#         with:
#           path: .

#       - name: Deploy to Github Pages
#         uses: actions/deploy-pages@v2

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # change if your files are inside /build or /dist

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2
